server:
  port: 8502



spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: korayaks
    password: korayaks
    cloud:
      stream:
        binding:
          output:
            destination: msqueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
